---
- name: Gather System Facts
  ansible.builtin.setup:
    gather_subset:
      - system
  when: ansible_facts.system is not defined

- name: Include Windows Tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ ansible_facts.system }}/main.yml"
  when: ansible_facts.system == 'Win32NT'
