---
- name: Gather System Facts
  ansible.builtin.setup:
    gather_subset:
      - system
  when: ansible_system is not defined

- name: Include Linux Tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/Linux/main.yml"
  when: ansible_system == 'Linux'